#!/bin/bash

declare -A app_icons=(
    ["kitty"]="%{F#E0DEF4} %{F-}"
    ["tor"]="%{F#9317CF} %{F-}"
    ["i2psvc"]="%{F#15C002} %{F-}"
    ["i2pd"]="%{F#15C002} %{F-}"
    ["steam"]="%{F#C7D5E0} %{F-}"
    ["firefox"]="%{F#FF4400} %{F-}"
    ["librewolf"]="%{F#00ACFF} %{F-}"
    ["sublime_text"]="%{F#FFAA00} %{F-}"
    ["prismlauncher"]="%{F#33FF33}󰍳 %{F-}"
    ["simplescreen"]="%{F#FF3333} %{F-}"
    ["telegram"]="%{F#00AAFF} %{F-}"
    ["64gram-desktop"]="%{F#FFAAFF} %{F-}"
    ["ayugram-desktop"]="%{F#9570FF} %{F-}"
    ["chromium"]="%{F#669DF6} %{F-}"
    ["paru"]="%{F#AAFF00}󰏖 %{F-}"
    ["mocp"]="%{F#44BBFF} %{F-}"
    ["ssh"]="%{F#7F7DFF}󰌘 %{F-}"
    ["python"]="%{F#FFFF00} %{F-}"
    ["node"]="%{F#44FF44}󰎙 %{F-}"
    ["quodlibet"]="%{F#AAAAAA}󰝚 %{F-}"
    ["lf"]="%{F#F6C177} %{F-}"
    ["wget"]="%{F#77C1F6} %{F-}"
    ["vlc"]="%{F#FFB100}󰕼 %{F-}"
    ["gajim"]="%{F#77F6C1}󰟿 %{F-}"
    ["htop"]="%{F#FF55AA} %{F-}"
    ["Discord"]="%{F#7289DA}󰙯 %{F-}"
    ["micro"]="%{F#ebbcba} %{F-}"
    ["easyeffects"]="%{F#f03523} %{F-}"
)


is_running() {
    pgrep -x "$1" > /dev/null
}


get_output() {
    output=""
    for app in "${!app_icons[@]}"; do
        if is_running "$app"; then
            output+=" ${app_icons[$app]} "
        fi
    done
    echo "$output"
}


get_output

